package constant.interaction;

public interface DataConstant {

	// random
	int SUBMIT_RANDOM = 20;

	int SUBMIT_RANDOM_PERMIT = 21;
	int SUBMIT_RANDOM_DENY = 22;

	int SUBMIT_RANDOM_SUCCESS = 23;
	int SUBMIT_RANDOM_FAILED = 24;

	// 18.7.22
	int CHECK_SPECIFIC = 200;

	int CHECK_SPECIFIC_PERMIT = 201;
	int CHECK_SPECIFIC_DENY = 202;

	// specific
	int SUBMIT_SPECIFIC = 2000;

	int SUBMIT_SPECIFIC_PERMIT = 2001;
	int SUBMIT_SPECIFIC_DENY = 2002;

	int SUBMIT_SPECIFIC_SUCCESS = 2003;
	int SUBMIT_SPECIFIC_FAILED = 2004;

	int ALREDAY_SUBMIT = 25;
}
